version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false
    ports: 
      - 51773:1972
      - 52773:52773
      - 53773
      - 3200:3200
    volumes:
      - ./:/irisdev/app
